# Generated by Django 2.1.5 on 2019-09-21 08:16

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API KEY')),
                ('api_secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API SECRET KEY')),
                ('currency', models.CharField(max_length=50, verbose_name='ターゲット通貨')),
                ('max_quantity_rate', models.FloatField(default=0.5, verbose_name='取引上限%')),
                ('target_profit_rate', models.FloatField(default=0.5, verbose_name='取引施行利益')),
                ('auto_trading', models.BooleanField(default=False, verbose_name='自動取引')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='管理者')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='利用開始')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='orderId')),
                ('quantity', models.FloatField(verbose_name='base_数量')),
                ('quote_quantity', models.FloatField(verbose_name='quote_数量')),
                ('expected_rate', models.FloatField(verbose_name='期待していたレート')),
                ('time', unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ('status', models.CharField(max_length=100, verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
            },
        ),
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '注文シナリオ',
                'verbose_name_plural': '注文シナリオ',
            },
        ),
        migrations.CreateModel(
            name='OrderSequenceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_profit', models.FloatField(verbose_name='想定利益')),
                ('profit', models.FloatField(verbose_name='利益')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OrderSequence')),
                ('t1_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_t1', to='core.Order')),
                ('t2_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_t2', to='core.Order')),
                ('t3_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_t3', to='core.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'シナリオ実行結果',
                'verbose_name_plural': 'シナリオ実行結果',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='通貨')),
                ('from_currency', models.CharField(max_length=10, verbose_name='元通貨')),
                ('to_currency', models.CharField(max_length=10, verbose_name='取得通貨')),
                ('side', models.CharField(max_length=10, verbose_name='サイド')),
            ],
            options={
                'verbose_name': 'シンボル',
                'verbose_name_plural': 'シンボル',
            },
        ),
        migrations.AddField(
            model_name='ordersequence',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myseq_t1', to='core.Symbol', verbose_name='t1'),
        ),
        migrations.AddField(
            model_name='ordersequence',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myseq_t2', to='core.Symbol', verbose_name='t2'),
        ),
        migrations.AddField(
            model_name='ordersequence',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myseq_t3', to='core.Symbol', verbose_name='t3'),
        ),
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Symbol', verbose_name='シンボル'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
    ]
