# Generated by Django 2.1.5 on 2019-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='btc', max_length=50, verbose_name='ターゲット通貨'),
            preserve_default=False,
        ),
    ]
