# Generated by Django 2.1.5 on 2019-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset', models.CharField(max_length=10, verbose_name='base')),
                ('quote_asset', models.CharField(max_length=10, verbose_name='quote')),
            ],
        ),
    ]
