# Generated by Django 2.1.5 on 2019-09-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='ステータス'),
            preserve_default=False,
        ),
    ]
