# Generated by Django 2.1.5 on 2019-08-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_symbols'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symbols',
            new_name='Symbol',
        ),
    ]
