# Generated by Django 2.1.5 on 2019-09-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_rate',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=1, verbose_name='価格'),
            preserve_default=False,
        ),
    ]
