# Generated by Django 2.1.5 on 2019-09-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190922_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='エラーメッセージ'),
        ),
    ]
