# Generated by Django 2.1.5 on 2019-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190805_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='side',
            field=models.CharField(default='hoge', max_length=10, verbose_name='サイド'),
            preserve_default=False,
        ),
    ]
