# Generated by Django 2.1.5 on 2019-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_symbol_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(default=1, max_length=20, verbose_name='通貨'),
            preserve_default=False,
        ),
    ]
