# Generated by Django 2.1.5 on 2019-09-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_fee_rate',
            field=models.FloatField(default=0.075, verbose_name='取引手数料'),
        ),
    ]
