# Generated by Django 2.1.5 on 2019-08-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_symbol_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myseq_t1', to='core.Symbol', verbose_name='t1')),
                ('t2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myseq_t2', to='core.Symbol', verbose_name='t2')),
                ('t3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myseq_t3', to='core.Symbol', verbose_name='t3')),
            ],
        ),
    ]
