# Generated by Django 2.1.5 on 2019-09-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_transaction_fee_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quote_quantity',
            field=models.FloatField(null=True, verbose_name='quote_数量'),
        ),
    ]
