# Generated by Django 2.1.5 on 2019-08-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ordersequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='base_asset',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='quote_asset',
        ),
        migrations.AddField(
            model_name='symbol',
            name='from_currency',
            field=models.CharField(default=1, max_length=10, verbose_name='元通貨'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='to_currency',
            field=models.CharField(default=1, max_length=10, verbose_name='取得通貨'),
            preserve_default=False,
        ),
    ]
