# Generated by Django 2.1.5 on 2019-09-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190923_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersequenceresult',
            name='profit',
            field=models.FloatField(null=True, verbose_name='利益'),
        ),
    ]
