# Generated by Django 2.1.5 on 2019-08-27 05:28

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190824_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='orderId')),
                ('quantity', models.FloatField(verbose_name='base_数量')),
                ('quote_quantity', models.FloatField(verbose_name='quote_数量')),
                ('expected_rate', models.FloatField(verbose_name='期待していたレート')),
                ('time', unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Symbol', verbose_name='シンボル')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSequenceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(verbose_name='利益')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OrderSequence')),
                ('t1_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_t1', to='core.Order')),
                ('t2_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_t2', to='core.Order')),
                ('t3_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_t3', to='core.Order')),
            ],
        ),
    ]
