# Generated by Django 2.1.5 on 2019-09-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190923_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersequenceresult',
            name='profit',
        ),
    ]
