# Generated by Django 2.1.5 on 2019-08-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190827_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
        migrations.AlterModelOptions(
            name='ordersequence',
            options={'verbose_name': '注文シナリオ', 'verbose_name_plural': '注文シナリオ'},
        ),
        migrations.AlterModelOptions(
            name='ordersequenceresult',
            options={'verbose_name': 'シナリオ実行結果', 'verbose_name_plural': 'シナリオ実行結果'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'verbose_name': 'シンボル', 'verbose_name_plural': 'シンボル'},
        ),
    ]
