# Generated by Django 2.1.5 on 2019-09-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_ordersequenceresult_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quote_quantity',
        ),
    ]
