# Generated by Django 2.1.5 on 2019-09-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_order_quote_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersequenceresult',
            name='expected_profit',
        ),
    ]
