# Generated by Django 2.1.5 on 2019-08-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190828_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_quantity',
            field=models.FloatField(default=0.5, verbose_name='取引上限%'),
        ),
    ]
