# Generated by Django 2.1.5 on 2019-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_ordersequenceresult_expected_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_active_scenario',
            field=models.IntegerField(default=10, verbose_name='最大シナリオ数'),
        ),
    ]
