# Generated by Django 2.1.5 on 2019-08-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190828_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersequenceresult',
            name='expected_profit',
            field=models.FloatField(default=0, verbose_name='想定利益'),
            preserve_default=False,
        ),
    ]
