# Generated by Django 2.1.5 on 2019-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_max_active_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scenario_unit',
            field=models.FloatField(default=0.2, verbose_name='unit'),
        ),
    ]
