# Generated by Django 2.1.5 on 2019-08-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ordersequenceresult_expected_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_trading',
            field=models.BooleanField(default=False, verbose_name='自動取引'),
        ),
    ]
