# Generated by Django 2.1.5 on 2019-08-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_auto_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_profit_rate',
            field=models.FloatField(default=0.5, verbose_name='取引施行利益'),
        ),
    ]
