# Generated by Django 2.1.5 on 2019-08-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_target_profit_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='max_quantity_perc',
            new_name='max_quantity_rate',
        ),
    ]
