# Generated by Django 2.1.5 on 2019-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersequenceresult',
            name='profit',
            field=models.FloatField(default=0, verbose_name='利益'),
            preserve_default=False,
        ),
    ]
