# Generated by Django 2.1.5 on 2019-09-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ordersequenceresult_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersequenceresult',
            name='profit',
        ),
    ]
