# Generated by Django 2.1.5 on 2019-09-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_ordersequenceresult_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.AddField(
            model_name='user',
            name='do_bnb',
            field=models.BooleanField(default=True, verbose_name='BNB'),
        ),
        migrations.AddField(
            model_name='user',
            name='do_btc',
            field=models.BooleanField(default=True, verbose_name='BTC'),
        ),
        migrations.AddField(
            model_name='user',
            name='do_eth',
            field=models.BooleanField(default=True, verbose_name='ETH'),
        ),
        migrations.AddField(
            model_name='user',
            name='do_usd',
            field=models.BooleanField(default=True, verbose_name='USD'),
        ),
    ]
