# Generated by Django 2.1.5 on 2019-09-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190928_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bnb_unit_amount',
            field=models.FloatField(default=0.001),
        ),
        migrations.AddField(
            model_name='user',
            name='btc_unit_amount',
            field=models.FloatField(default=0.001),
        ),
        migrations.AddField(
            model_name='user',
            name='eth_unit_amount',
            field=models.FloatField(default=0.001),
        ),
        migrations.AddField(
            model_name='user',
            name='usd_unit_amount',
            field=models.FloatField(default=0.001),
        ),
    ]
