# Generated by Django 2.1.5 on 2019-10-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_user_scenario_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usd_unit_amount',
            new_name='usdt_unit_amount',
        ),
    ]
